### ISSUE TITLE
Problème de traduction

### ISSUE THREAD

**Issue by claudiodsf** [EarthPortal/ontoportal_web_ui#12]
Le bouton "Vizualize" devrait être plutôt "Visualize": https://github.com/EarthPortal/ontoportal_web_ui/blob/40b4b6da7a819c06009fdd9e978e1271125ca617/config/locales/en.yml#L932

**Comment by galviset** [comment]
Corrigé et en production:
![image](https://github.com/user-attachments/assets/c39162f3-f7c9-4374-8016-30b2d7ec41f2)

Merci
